name: Hexo deploy

on:
  push:
    branches:
      - raw

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js (.tool-versions)
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: prepare build env
        env:
          GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'gythialy'
          git config --global user.email 'gythialy@users.noreply.github.com'
          npm i -g hexo-cli
          npm i
      - name: deploy to github
        run: |
          hexo generate && hexo deploy
