name: Hexo deploy

on:
  push:
    branches:
      - raw
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Read .tool-versions
        id: tool-versions
        run: echo "BUN_VERSION=$(grep '^bun' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.tool-versions.outputs.BUN_VERSION }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        run: bun install

      - name: Cache Hexo public folder
        uses: actions/cache@v4
        with:
          path: public
          key: ${{ runner.os }}-hexo-public-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-hexo-public-

      - name: Build
        run: bun run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public
          retention-days: 30

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
